Desktop/web_2/mysite/api/urls.py
from django.urls import include, path
from api import views
from rest_framework.urlpatterns import format_suffix_patterns


# urlpatterns = [
#     path('snippets/', views.snippet_list),
#     path('snippets/<int:pk>/', views.snippet_detail),
# ]
urlpatterns = [
    #이전에는 함수 - 현재는 class 로 작동하도록 urls연결 
    path('', views.api_root),
    path('snippets/', views.SnippetList.as_view(), name="snippet-list"),
    path('snippets/<int:pk>/', views.SnippetDetail.as_view(), name="snippet-detail"),
    path('users/', views.UserList.as_view(), name="user-list"),
    path('users/<int:pk>/', views.UserDetail.as_view(), name="user-detail"),
    path('posts/', views.PostList.as_view(), name="post-list"),
    path('posts/<int:pk>/', views.PostDetail.as_view(), name="post-detail"),
    path('questions/', views.QuestionList.as_view(), name="question-list"),
    path('questions/<int:pk>/', views.QuestionDetail.as_view(), name="question-detail"),
    path('profile/', views.profile, name="profile"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

Desktop/web_2/mysite/blog/urls.py
from django.http import HttpRequest, HttpResponse
from django.urls import include, path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.index),    
    path('post_list/', views.post_list, name="list"),
    path('post_detail/<int:pk>/', views.post_detail, name="detail"),
    path('post_create/', views.post_create, name="create"),
   # path('post_list', ListView.as_viewpost_list)
    path('api/post/',views.api_post_list,name="api_list"),
    path('api/post/<int:pk>/',views.api_post,name="api_one")

]

Desktop/web_2/mysite/mysite/urls.py
# """mysite URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path , include

# urlpatterns = [
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('admin/', admin.site.urls),
#     path('blog/', include('blog.urls'), name="blog"),
#     path('toy/', include('toy.urls'), name="toy"),
#     path('polls/', include('polls.urls'), name="polls"),
#     path('api-auth/', include('rest_framework.urls')),
# ]

from django.urls import path, include, re_path
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets

from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib import admin

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'), name="blog"),
    path('toy/', include('toy.urls'), name="toy"),
    path('polls/', include('polls.urls'), name="polls"),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

Desktop/web_2/mysite/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model) :
    title = models.CharField(max_length=100)
    content = models.TextField()

Desktop/web_2/mysite/blog/forms.py
from django import forms
from . import models


# //모델 전체를 처리할때 - 장고가 폼을 처리할때 

# class PostForm(forms.ModelForm):
#     class Meta:
#         model = models.Post
#         fields = "__all__"

class PostForm(forms.Form) :
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea())

class PostModelForm(forms.ModelForm):

    class Meta:
        model = models.Post
        fields = ['title','content']
        #모델을 선택해서 만들수있음 . 

Desktop/web_2/mysite/blog/views.py
import json
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from . import models 
from . import forms


def index(req): 
    return HttpResponse('blog')

def post_list(req):
    # posts = [
    #     {'pk': 1, 'title': 'html', 'content': 'html is ...'},
    #     {'pk': 2, 'title': 'css', 'content': 'css is ...'},
    #     {'pk': 3, 'title': 'javascipt', 'content': 'javascipt is ...'},
    #     {'pk': 4, 'title': 'python', 'content': 'python is ...'},
    #     {'pk': 5, 'title': 'django', 'content': 'django is ...'},
    # ]
    posts = models.Post.objects.all()
    return render(req, 'blog/post_list.html', {"post_list": posts})
    # Create your views here.

def post_detail(req, pk):
    post = models.Post.objects.get(pk=pk)
    return render( req, 'blog/post_detail.html', {"post": post})


def post_create(req):
    if req.method == "POST":
        form = forms.PostModelForm(req.POST)
        if form.is_valid():
            form.save()
        return redirect("/blog/post_list/")
    else:
        form = forms.PostForm()

    return render(req, 'blog/post_create.html', {'form': form})

from django.views.decorators.csrf import csrf_exempt
from django.forms.models import model_to_dict

#get 일때 지원함 
@csrf_exempt
def api_post_list(req):
    if req.method == 'GET':
        posts = models.Post.objects.all()
        return JsonResponse({"results": list(posts.values())})
    elif req.method == 'POST':
        body = json.loads(req.body.decode('utf-8'))
        p=models.Post(title=body['title'], content = body['content'])
        p.save()
        return JsonResponse({"results":model_to_dict(p)})
    else :
        return HttpResponse(status=405)


from django.forms.models import model_to_dict
@csrf_exempt
def api_post(req,pk):
    if req.method == 'GET':
        post = models.Post.objects.filter(pk=pk)
        if not post:
            return JsonResponse(status=404)
        return JsonResponse({"results": model_to_dict(post)})
    elif req.method == 'PUT':
        body = json.loads(req.body.decode('utf-8'))
        post = models.Post.objects.filter(pk=pk)
        if not post:
            return HttpResponse(status=404)
        p = post[0]
        p.title = body['title']
        p.content = body['content']
        p.save()
        return JsonResponse({"results": model_to_dict(p)})
    elif req.method == 'DELETE':
        post = models.Post.objects.filter(pk=pk)
        if not post:
            return HttpResponse(status=404)
        p = post[0]
        p.delete()
        return JsonResponse({"results": "ok"})
    else:
        return JsonResponse(status=405)

        #   post = models.Post(title=req.Post["title"], 
        #   content=req.models.Post['content'])

    # if req.method == "POST" :
    #     post = models.Post(title=req.Post["title"], content=req.models.Post
    #     ['content'])
    #     post.save()

    return render( req, 'blog/post_create.html', {'form':form})



# def post_form(req):
#     form = forms.PostForm
#         post = models.Post(title=req.Post["title"], content=req.models.Post
#         ['content'])
#         post.save()
#         return redirect("/blog/post_list/")

#     return render( req, 'blog/post_create.html')

  # print(form.cleaned_data)
            # post = models.Post(**form.cleaned_data) 

Desktop/web_2/mysite/blog/templates/blog/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Blog-post create </title>
</head>
<body>
    <h1>Post create</h1>
    <form method="post">
        {% csrf_token %}
        <table>{{ form }}</table>
        <div><input type="submit" value="저장"></div>
    </form>
</body>
</html>


            <!-- {{p.pk}}. [{{p.title}}] : {{p.content}}</li> -->
     <!-- <div><input type="text" id="title" name="title"></div>
        <div><textarea id="content" name="content"></textarea></div> -->

Desktop/web_2/mysite/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Blog-post List </title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <div>{{post.content}}</div>
       <ul>
        {% for p in post_list %}
        <li><a href="{% url 'blog:list' %}">{{forloop.counter}} {{p.title}}</a></li>
        {% endfor%}
    </ul>
</body>
</html>


            <!-- {{p.pk}}. [{{p.title}}] : {{p.content}}</li> -->

Desktop/web_2/mysite/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Post List</title>
</head>
<body>
    <h1>Post List</h1>
    <ul>
        {% for p in post_list %}
            <li><a href="{% url 'blog:detail' p.pk %}">{{ forloop.counter }} {{ p.title }}</a></li>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'blog:create' %}">새글쓰기</a>
</body>
</html>

<!-- <!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Blog-post List </title>
</head>
<body>
    <h1>Post List</h1>
    <ul>
        {% for p in post_list %}
        <li><a href="/blog/post_detail/{{p.pk}}">{{forloop.counter}} {{p.title}}</a></li>
        <li><a href="{% url 'blog:detail' p.pk %}">{{ forloop.counter }} {{ p.title }}</a></li>

        {% endfor%}
    </ul>
    <a href="{% url }"></a>
</body>
</html>


            {{p.pk}}. [{{p.title}}] : {{p.content}}</li> -->